server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cvdesign
    password: Cv521.
    url: jdbc:mysql://127.0.0.1:3306/cv_design?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&&enabledTLSProtocols=TLSv1.2
  redis:
    host: 127.0.0.1
    port: 6379
    password: tanyongfeng13666
logging:
  level:
    root: info
# 开启 MyBatis Plus SQL 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



pagehelper:
  helperDialect: mysql
  reasonable: true # 修改默认值